name: 02 - workflow events


on: 
  push:
  pull_request: 
  schedule:
    - cron: '*/5 0 * * *'
  workflow_dispatch: 
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
     - name: Show the trigger
       run: echo "Ive been triigered by ${{ github.event_name }}"
